config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  resources :users, only: [:edit, :update]
  
  resources :institutions do
    resources :campaigns, only: [:new, :create]
  end

  resources :campaigns, only: [:show, :index, :edit, :update, :destroy] do
    resources :donations, only: [:new, :create]
    resources :accountabilities, only: [:create, :new, :edit]
  end

  resources :accountabilities, only: [:show] do
    resources :donations, only: [:show] do
      resources :reviews, only: [:new, :create]
    end
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6 col-lg-4 p-3">
        <%= image_tag('sos-donations-logo.png', style: "width:90px;") %>
      </div>
      <div class="footer-info col-sm-12 col-md-6 col-lg-4 p-3">
        <span class="my-5">Copyright 2021 Capybaras Enterprise</span>
        <br>
        <span class="mt-5">Ladeira da Glória 26, Rio de Janeiro</span>
      </div>
      <div class="footer-info col-sm-12 col-md-6 col-lg-2 p-3">
        <span>Contact us</span>
        <br>
        <span>Work with us</span>
      </div>
      <div class="footer-links col-sm-12 col-md-6 col-lg-2 p-3">
        <a href="#"><i class="fab fa-youtube"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-tiktok"></i></a>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-primary navbar-lewagon">
  <%= link_to "/", class: "navbar-brand ml-5" do %>
    <%= image_tag('sos-donations-logo.png', id: "nav-logo") %>
    <span class="align-bottom px-2" style="font-size: 1.3rem;">Building a better world</span>
  <% end %>
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     <%= link_to campaigns_path, class: "nav-link"  do %>
          <i class="h4 fas fa-hands-helping px-2"></i>Campaigns
        <% end %>
      <li class="nav-item">
        <%= link_to institutions_path, class: "nav-link"  do %>
          <i class="h4 fas fa-building px-2"></i>Institutions
        <% end %>
      </li>
      <% if user_signed_in? %>
     <!--    aqui tinha um link para button -->
        <li class="nav-item">
        </li>
        <li class="nav-item dropdown ml-3">
          <% if current_user.photo.present? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", style: "cursor: pointer;", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag('neutral-avatar.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Donations", dashboard_path(results_query: 'donations'), class: "dropdown-item" %>
            <%# <%= link_to "Create a campaign", new_institution_campaign_path(@institution), class: "dropdown-item" %>
            <%= link_to "Manage account", "/dashboard", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link"  do %>
            <i class="fas fa-user px-2"></i>Login
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>