config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  resources :users, only: [:edit, :update]
  
  resources :institutions do
    resources :campaigns, only: [:new, :create]
  end

  resources :campaigns, only: [:show, :index, :edit, :update, :destroy] do
    resources :donations, only: [:new, :create]
    resources :accountabilities, only: [:create, :new, :edit]
  end

  resources :accountabilities, only: [:show] do
    resources :donations, only: [:show] do
      resources :reviews, only: [:new, :create]
    end
  end

end

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="user-account card p-4 col-sm-12 col-md-3 col-lg-4">
      <div class="d-flex">
        <% if current_user.photo.present? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar-dashboard dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag('neutral-avatar.png') %>
        <% end %>
        <div class="user-account-info ml-3" style="display:inline-block; align-self:flex-end; width:100%;">
          <h4><b><%= "#{current_user.first_name} #{current_user.last_name}" %></b></h4>
          <p><%= current_user.email %></p>
          <div class="d-flex justify-content-start">
            <%= link_to edit_user_path(current_user) do %>
              <i class="fas fa-pencil-alt mr-4"></i>
            <% end %>
            <%= link_to registration_path(current_user), method: :delete, data: { confirm: "Are you sure?"} do %>
              <i class="fa fa-trash"></i>
            <%end%>
          </div>
        </div>
      </div>
      <%= link_to 'Create a new institution',  new_institution_path,  class: "btn btn-primary", style: 'margin-top:50px' %>
    </div>

    <div class="col-sm-12 col-md-9 col-lg-8">
      <div class="navbar navbar-expand-lg navbar-light bg-light" id="navbar-account">
        <ul class="navbar-nav mr-auto px-4">
          <% if @results == 'donations' %>
            <li class="nav-item active">
          <% else %>
            <li class="nav-item">
          <% end %>
          <%= link_to "Donations", dashboard_path(results_query: 'donations'), class: "nav-link" %>
          </li>
          <% if @results == 'institutions' %>
            <li class="nav-item active">
          <% else %>
            <li class="nav-item">
          <% end %>
          <%= link_to "Institutions", dashboard_path(results_query: 'institutions'), class: "nav-link" %>
          </li>
          <% if @results == 'campaigns' %>
            <li class="nav-item active">
          <% else %>
            <li class="nav-item">
          <% end %>
          <%= link_to "Campaigns", dashboard_path(results_query: 'campaigns'), class: "nav-link" %>
          </li>
          <% if @results == 'accountabilities' %>
            <li class="nav-item active">
          <% else %>
            <li class="nav-item">
          <% end %>
          <%= link_to "Accountabilities", dashboard_path(results_query: 'accountabilities'), class: "nav-link" %>
          </li>
        </ul>
      </div>

      <div class="dashboard-results dashboard-top-buffer mx-3">
        <% if @results == 'donations' %>
          <% @donations.each do |donation| %>
            <div class="dashboard-results-card card my-4">
              <div class="flex-area d-flex p-3">
                <div class="d-flex">
                  <div>
                    <% if current_user.photo %>
                      <%= cl_image_tag donation.campaign.photos.first.key, class: "avatar-dash " %>
                    <% else %>
                      <%= image_tag('neutral-institution.jpg') %>
                    <% end %>
                  </div>
                  <div class="user-account-details ml-3">
                    <h4><b><%= donation.campaign.name %></b></h4>
                    <span><%= donation.campaign.description %></span>
                    <div class="user-account-info mt-3">
                      <h5><b> <i class="fas fa-hand-holding-medical mr-2"></i><%= donation.donation_expression %></b></h5 >
                    </div>
                    <div class="user-account-button d-flex justify-content-between">
                      <div>
                        <span class="badge badge-primary"><i>Donated at: <%= donation.created_at.to_date %></i></span>
                      </div>
                      <%= link_to campaign_path(donation.campaign) do %>
                        <i class="h3 fas fa-search-plus"></i>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="dashboard-results dashboard-top-buffer mx-3">
        <% if @results == 'institutions' %>
          <% @institutions.each do |institution| %>
            <div class="dashboard-results-card card my-4">
              <div class="flex-area d-flex p-3">
                <div class=" user-account-details ml-3">
                  <div class="d-flex">
                    <div>
                      <% if institution.photos.present? %>
                        <%= cl_image_tag institution.photos.first.key, class: "avatar-logo " %>
                      <% else %>
                        <%= image_tag('neutral-institution.jpg') %>
                      <% end %>
                    </div>
                    <div class="ml-3">
                      <h4><b><%= institution.name %></b></h4>
                      <span><%= institution.address %></span> <br>
                      <span><%= institution.cnpj %></span>
                      <div>
                        <span class="badge badge-primary"><i>Founded at: <%= institution.created_at.to_date %></i></span>
                      </div>
                    </div>
                  </div>
                  <hr>
                  <span><%= institution.description %></span>
                  <div class="user-account-button d-flex justify-content-end">
                    <%= link_to 'New campaign', new_institution_campaign_path(institution), class: 'btn btn-primary mr-4'%>
                     <%= link_to edit_institution_path(institution) do%>
                        <i class="h3 fas fa-edit mr-3"></i>
                      <% end %>
                    <%= link_to institution_path(institution) do %>
                      <i class="h3   fas fa-search-plus"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="dashboard-results dashboard-top-buffer mx-3">
        <% if @results == 'campaigns' %>
          <% @campaigns.each do |campaign| %>
            <div class="dashboard-results-card card my-4">
              <div class="flex-area d-flex p-3">
                  <div>
                    <% if campaign.photos.present? %>
                      <%= cl_image_tag campaign.photos.first.key, class: "avatar-logo " %>
                    <% else %>
                      <%= image_tag('neutral-institution.jpg') %>
                    <% end %>
                  </div>
                <div class="user-account-details ml-3">
                  <h4><b><%= campaign.name %></b></h4>
                  <div>
                    <span class="badge badge-primary"><%= campaign.category%></span>
                    <span class="badge badge-primary"><i>Created at: <%= campaign.created_at.to_date %></i></span>
                  </div>
                  <hr>
                  <span><%= campaign.description %></span>
                </div>
              </div>
              <div class="user-account-button d-flex justify-content-end mr-3 mb-2">
                <%= link_to 'New accountability', new_campaign_accountability_path(campaign, @accontability ), class: 'btn btn-primary mr-4 mb-2'%>
                <%= link_to edit_campaign_path(campaign) do%>
                  <i class="h3 fas fa-edit mr-3"></i>
                <% end %>

                <%= link_to campaign_path(campaign) do %>
                  <i class="h3 fas fa-search-plus "></i>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="dashboard-results dashboard-top-buffer mx-3">
        <% if @results == 'accountabilities' %>
          <% @accountabilities.each do |accountability| %>
            <div class="dashboard-results-card card my-4">
              <div class="flex-area d-flex p-3">

                   <div>
                      <% if accountability.photos.present? %>
                        <%= cl_image_tag accountability.photos.first.key, class: "avatar-logo " %>
                      <% end %>
                    </div>
                <div class="user-account-details ml-3">
                  <h4><b> Accoutability for <%= accountability.campaign.name %></b></h4>
                  <div>
                    <span class="badge badge-primary"><i>Created at: <%= accountability.created_at.to_date %></i></span>
                  </div>
                </div>
              </div>
                <div class="user-account-button d-flex justify-content-end mr-3 mb-1">
                    <%= link_to accountability_path(accountability.id) do %>
                      <i class="h3 fas fa-search-plus"></i>
                    <% end %>
                  </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="landing-banner">
  <div class="landing-banner-text">
    <h4>Many people are waiting for your help...</h4>
    <h1 style="font-size: 3.5rem">Let's Build a better world</h1>
    <%= link_to "Join us!", new_user_registration_path, class: "btn btn-primary w-25 mt-4 p-2", style: "font-size: 1rem; color: white" if !user_signed_in?%>
  </div>
</div>
<div class="container", style="background-color: #EAF6DE">
  <div class="row shadow-home">
    <div class="col-4 donation-type", style="background-color: #44a245">
      <%= link_to campaigns_path(type_donation: "Fundrising" ) do %>
        <h2>Fundrising</h2>
        <span>Help social acts and projects by given funds!</span>
      <% end %>
    </div>
    <div class="col-4 donation-type" style="background-color:  #5dbb5f">
      <%= link_to campaigns_path(type_donation: "Donation" ) do %>
        <h2>Donation</h2>
        <span>Donate food, clouthes and goods to those who really needs it!</span>
      <% end %>
    </div>
    <div class="col-4 donation-type" style="background-color: #44a245">
      <%= link_to campaigns_path(type_donation: "Volunteer" ) do %>
        <h2>Volunteer</h2>
        <span>Give some of your time to help important actions!</span>
      <% end %>
    </div>
  </div>

  <h1 class="home-title" >Find Campaigns</h1>

  <div class="row">
    <% @CATEGORIES.each do |category| %>
    <div class="card-grid col-sm-12 col-md-6 col-lg-3 donation-categories">
      <%= link_to campaigns_path(category: category[:name] ) do %>
        <%= image_tag(category[:filename], class: "card-img-top") %>
        <div class="card-body donation-categories-info">
          <span><%= category[:name] %></span>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>

  <h1 class="home-title">Urgent campaigns</h1>

  <div id="carousel-indicators-urgent" class="carousel slide mt-3" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carousel-indicators-urgent" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-indicators-urgent" data-slide-to="1"></li>
      <li data-target="#carousel-indicators-urgent" data-slide-to="2"></li>
    </ol>
    <div id="carousel-campaign" class="carousel-inner">
      <% @urgent_campaigns.each do |campaign|%>
        <% if campaign == @urgent_campaigns.first %>
          <div class="carousel-item active">
        <% else %>
          <div class="carousel-item">
        <% end %>
          <div class="card card-campaign">
            <%= link_to campaign_path(campaign.id), class: "link-carousel d-block w-75" do %>
              <%= cl_image_tag campaign.photos.first.key, class: "card-img-top" %>
              <div class="d-none d-md-block card-body d-flex justify-content-around">
                <h2><%= campaign.name %></h2>
                <p class="badge badge-warning"><%= campaign.indicator %></p><br>
                <p class="badge badge-warning">Still missing: <%= campaign.missing_expression %></p><p class="mx-4 badge badge-warning">help us to complete it!</p>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carousel-indicators-urgent" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-indicators-urgent" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <h1 class="home-title">Donation's Accountability Reviews</h1>

  <% @latest_reviews.each do |review| %>
    <div class="reviews-home p-3 mt-3 mb-5 d-flex justify-content-start py-4">
      <div class="review-left ml-4">
        <%= cl_image_tag review.donation.user.photo.key, class: "avatar-home" %><br>
        <span style="font-size: 1.2rem"><b><%= "#{review.donation.user.first_name} #{review.donation.user.last_name}" %></b></h5><br>
        <span class="badge badge-success", style="font-size: 0.8rem"><%= "#{review.donation.user.donations.count} donations" %></span><br>
         <div class="review-comments">
          <b><span style="font-size: 1rem"><%= review.comment %><br>
            <% review.star.times do %>
              <i class="fas fa-star star text-warning ", style= "text-shadow: 2px 2px 4px #012F00;"></i>
            <% end %>
          </span></b>
        </div>
        <span style="font-size: 0.8rem"><b><%= "Member since: #{review.donation.user.created_at.strftime("%d/%m/%Y")}" %></b></span><br>
      </div>
      <div class="ml-5" >
        <span><b>Reviewing on: </b></span><br>
        <%= cl_image_tag review.accountability.campaign.photos.first.key, class: "img-home" %><br>
        <span class="badge badge-warning mt-2", style="font-size: 0.8rem"><%= review.accountability.campaign.name %></span><br>
      </div>
    </div>
  <% end %>
</div>