config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  resources :users, only: [:edit, :update]
  
  resources :institutions do
    resources :campaigns, only: [:new, :create]
  end

  resources :campaigns, only: [:show, :index, :edit, :update, :destroy] do
    resources :donations, only: [:new, :create]
    resources :accountabilities, only: [:create, :new, :edit]
  end

  resources :accountabilities, only: [:show] do
    resources :donations, only: [:show] do
      resources :reviews, only: [:new, :create]
    end
  end

end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :institution
  has_many :donations
  has_many :accountabilities

  CATEGORIES = ["Coronavirus", "Hunger and Poverty", "Health", "Eldery", "Children", "Education", "Emergency Situations", "Animal causes"]
  validates :category, presence: true, inclusion: { in: CATEGORIES, message: "%{value} is not permited category" }
  validates :name, presence: true
  validates :description, presence: true
  validates :total, presence: true

  has_many_attached :photos

  def total_expression
    if self.type_donation == "Volunteer"
      "Objective: #{self.total} Voluntaries"
    elsif self.type_donation == "Fundrising"
      "Objective: R$#{self.total}"
    else
      "Objective: #{self.total} Donations"
    end
  end

  def indicator
    if self.type_donation == "Volunteer"
      "#{(self.raised / self.total.to_f * 100).floor}%  already Volunteered"
    else
      "#{(self.raised / self.total.to_f * 100).floor}%  already Donated!"
    end
  end

  def missing_expression
    qtde_missing = self.raised >= self.total ? 0 : (self.total - self.raised)
    if self.type_donation == "Volunteer"
      "#{qtde_missing} #{'Volunteer'.pluralize(qtde_missing)}"
    elsif self.type_donation == "Fundrising"
      "R$: #{qtde_missing}"
    else
      "#{qtde_missing} #{'Donation'.pluralize(qtde_missing)}"
    end
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: %i[show edit update]

  def index
    @campaigns = Campaign.all
    @campaigns = @campaigns.where(institution_id: params[:institution_id]) if params[:institution_id]
    @campaigns = @campaigns.where(category: params[:category]) if params[:category]
    @campaigns = @campaigns.where(type_donation: params[:type_donation]) if params[:type_donation]

    if !params[:institution_id] && !params[:category] && !params[:type_donation]
      @campaigns_title = "All Campaigns in SOS Donations!"
    end
    @campaigns_title = "Campaigns from #{Institution.find(params[:institution_id]).name}" if params[:institution_id]
    if @campaigns_title
      @campaigns_title = "#{@campaigns_title} ,in #{params[:category]}" if params[:category]
    elsif params[:category]
      @campaigns_title = "Campaigns in #{params[:category]}"
    end
    if @campaigns_title
      @campaigns_title = "#{@campaigns_title} ,in #{params[:type_donation]}" if params[:type_donation]
    elsif params[:type_donation]
      @campaigns_title = "Campaigns in #{params[:type_donation]}"
    end
  end

  def show; end

  def new
    @institution = Institution.find(params[:institution_id])
    @campaign = Campaign.new
    authorize @campaign
  end

  def create
    @institution = Institution.find(params[:institution_id])
    @campaign = Campaign.new(campaign_params)
    @campaign.institution = @institution
    if @campaign.photos.empty?
      @campaign.photos.attach(io: File.open('app/assets/images/neutral-institution.jpg'),
                              filename: 'neutral-institution.jpg', content_type: 'image/png')
    end
    @campaign.raised = 0
    authorize @campaign
    if @campaign.save
      redirect_to campaign_path(@campaign)
    else
      render :new
    end
  end

  def edit; end

  def update
    @campaign.update(campaign_params)
    redirect_to campaign_path(@campaign)
  end

  private

  def set_campaign
    @campaign = Campaign.find(params[:id])
    if @campaign.type_donation == "Volunteer"
      @donation_verb = "Volunteer"
    else
      @donation_verb = "Donate"
    end
    authorize @campaign
  end

  def campaign_params
    params.require(:campaign).permit(:name, :description, :category, :total, :type_donation, :photos)
  end
end

app/views/campaigns/_form.html.erb
<%= simple_form_for [ @institution, @campaign ] do |f| %>
          <%= f.input :name, placeholder: 'Name of Campaign' %>
          <%= f.input :description, placeholder: 'Type a description about the capaign' %>
          <%= f.input :total %>
          <%= f.input :category, as: :select, collection: ["Coronavirus", "Hunger and Poverty", "Health", "Eldery", "Children", "Education", "Emergency Situations", "Animal causes"], placeholder: 'Select one category' %>
          <%= f.input :type_donation, as: :select, collection: ["Fundrising", "Donation", "Volunteer"], placeholder: 'Select one type.' %>
          <%= f.input :photos, as: :file, input_html: { multiple: true }  %>
          <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/campaigns/edit.html.erb
<div class="container my-5 py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Edit campaign</h3>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/index.html.erb
<div class="container">
  <div class="mr- mt-4">
    <span class="badge badge-success" style="font-size: 2rem;"><strong><%= @campaigns_title %></b></span>
  </div>
  <div class="container mt-3">
    <div class="row mt-4">
	    <% @campaigns.each do |campaign| %>
        <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
          <div class="card my-3 card-campaign h-100 shadow" style="width: 18rem;">
             <% if campaign.photos.first.present? %>
                <%= cl_image_tag campaign.photos.first.key, class: "card-img p-2" %>
              <% else %>
                <%= image_tag('neutral-institution.jpg', class: "p-2") %>
              <% end %>

            <div class="card-body d-flex justify-content-between " style="width: 18rem; flex-direction: column;">
              <h4 class="card-title text-center"> <strong><%= campaign.name %></strong></h4>
              <div class="campaing-info">
                <div class="d-flex justify-content-around">
                  <span class="badge btn-primary"><%= campaign.category %></span>
                  <span class="badge btn-primary"><%= campaign.type_donation %></span>
                </div>
                <div class="progress mt-3">
                  <div class="progress-bar" role="progressbar" style="width: <%= campaign.raised / campaign.total.to_f * 100 %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"><%= campaign.raised %> / <%= campaign.total %></div>
                </div>
                  <% if campaign.raised >= campaign.total %>
                    <div class="d-flex justify-content-between mt-3">
                      <span class="badge btn-warning">Campagin Complete!</span>
                      <%= link_to campaign do %>
                        <i class="h4 fas fa-search-plus"></i>
                      <% end %>
                    </div>
                  <% else %>
                    <div class="d-flex justify-content-end mt-3">
                      <%= link_to campaign do %>
                      <i class="h4 fas fa-search-plus"></i>
                      <% end %>
                    </div>
                  <% end %>
                </div>
            </div>	
          </div>
        </div>
      <%end%>  
    </div>
  </div>
</div>

app/views/campaigns/new.html.erb
<div class="container my-5 py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new Campaign</h3>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/show.html.erb
<div class="container my-5">
  <div class="card d-flex p-3 shadow">
    <div class="d-flex justify-content-around ml-5 mr-5">
      <div class="container">
        <div class="mt-5">
          <h1 class="text-center"><b> <%= @campaign.name %></b> </h1>
        </div>
        <div class="my-2">
          <p class="text-justify"> <%= @campaign.description %>
          <div class="campaing-info">
            <div class="d-flex justify-content-around">
              <% if @campaign.raised >= @campaign.total %>
                <span class="badge btn-warning">Campagin Complete!</span>
              <% end %>
              <span class="badge btn-primary"><%= @campaign.category %></span>
              <span class="badge btn-primary"><%= @campaign.type_donation %></span>
            </div>
              <div class="progress mt-3">
                <div class="progress-bar" role="progressbar" style="width: <%= @campaign.raised / @campaign.total.to_f * 100 %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"><%= @campaign.raised %> / <%= @campaign.total %></div>
              </div>
           </div>
          <div class="d-flex justify-content-center mt-4">
            <div class="div">
              <% if @campaign.raised >= @campaign.total && @campaign.accountabilities.present? %>
                <%= link_to "Accountabilty", accountability_path(@campaign.accountabilities.first.id), class: 'btn btn-primary'%>
              <% else %>
                <%= link_to @donation_verb, new_campaign_donation_path(@campaign), class: "btn btn-primary"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="">
        <% if @campaign.photos.first.present? %>
          <%= cl_image_tag @campaign.photos.first.key, class: "card-img card-show-img p-2" %>
        <% else %>
          <%= image_tag('neutral-institution.jpg', class: "p-2") %>
        <% end %>
      </div>
    </div>

  </div>
</div>